/**
 * This class is generated by GenerationCodeUtil.
*/
package com.frank.chapter412.repository.test;

import org.apache.commons.lang3.tuple.Pair;
import org.jooq.Table;
import org.jooq.UpdatableRecord;
import org.springframework.stereotype.Repository;


import com.frank.chapter412.entity.test.tables.records.UserRecord;
import com.frank.chapter412.repository.TestBaseRepository;
import static com.frank.chapter412.entity.test.Tables.USER;

@Repository
public class UserRepository extends TestBaseRepository<UserRecord> {

    @Override
    protected Pair<Class<UserRecord>, Table<? extends UpdatableRecord>> mapping() {
        return Pair.of(UserRecord.class, USER);
    }

    public void AddUser(UserRecord userRecord){
        dslWrite.executeInsert(userRecord);
    }
}
