/**
 * This class is generated by jOOQ
 */
package com.frank.chapter412.entity.test;


import com.frank.chapter412.entity.test.tables.User;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in test
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>test.user</code>.
     */
    public static final User USER = com.frank.chapter412.entity.test.tables.User.USER;
}
